### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Jeremyop** [imqurex/Valorant-Triggerbot#1]
Traceback (most recent call last):
  File "C:\Users\000\Desktop\Valorant-Triggerbot-main\main.py", line 142, in <module>
    PopOff().hold()
  File "C:\Users\000\Desktop\Valorant-Triggerbot-main\main.py", line 128, in hold
    if is_pressed(TRIGGER):
  File "C:\Users\Anderson\AppData\Local\Programs\Python\Python39\lib\site-packages\keyboard\__init__.py", line 417, in is_pressed
    steps = parse_hotkey(hotkey)
  File "C:\Users\000\AppData\Local\Programs\Python\Python39\lib\site-packages\keyboard\__init__.py", line 358, in parse_hotkey
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "C:\Users\000\AppData\Local\Programs\Python\Python39\lib\site-packages\keyboard\__init__.py", line 358, in <genexpr>
    steps.append(tuple(key_to_scan_codes(key) for key in keys))
  File "C:\Users\000\AppData\Local\Programs\Python\Python39\lib\site-packages\keyboard\__init__.py", line 324, in key_to_scan_codes
    raise ValueError('Key {} is not mapped to any known key.'.format(repr(key)), e)
ValueError: ("Key 'Replace this first line with your hotkey.  e.g.  c   or   `   or even   ctrl' is not mapped to any known key.", ValueError("Key name 'replace this first line with your hotkey.  e.g.  c   or   `   or even   ctrl' is not mapped to any known key."))

**Comment by Jeremyop** [comment]
ok I fix it
it work
and maybe you can try to make esp

**Comment by Jeremyop** [comment]
so can you make esp?

**Comment by imqurex** [comment]
No sry. That's to hard and would be normal cheating.
